name: Build Custom Database

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  build_db:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build Custom Database for MiSTer Downloader
      run: set -o pipefail && curl --fail --location https://raw.githubusercontent.com/theypsilon/Downloader_DB-Template_MiSTer/main/.github/build_db.py | python3 -
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
